package com.thingtrack.myToolbar;

import java.io.Serializable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.terminal.gwt.client.MouseEventDetails;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class BoxToolbar extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout toolbarLayout;

	@AutoGenerated
	private Button btnPrint;

	@AutoGenerated
	private Button btnFilter;
	
	@AutoGenerated
	private Button btnAttach;

	@AutoGenerated
	private ComboBox cmdExport;

	@AutoGenerated
	private Label lblExport;

	@AutoGenerated
	private Embedded imgSeparatorGroup;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private int position = 0;
	
	// navigator button listeners
	@SuppressWarnings("unused")
	private ClickExportButtonListener listenerExportButton = null;
	@SuppressWarnings("unused")
	private ClickPrintButtonListener listenerPrintButton = null;
	@SuppressWarnings("unused")
	private ClickAttachButtonListener listenerAttachButton = null;
	@SuppressWarnings("unused")
	private ClickFilterButtonListener listenerFilterButton = null;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */	
	public BoxToolbar() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		btnFilter.setDescription("Filtrar Tabla");
		btnPrint.setDescription("Imprimir Tabla");
		btnAttach.setDescription("Adjuntar Fichero");
		
		setWidth("332px");
	}
	
	public void addListenerExportButton(ClickExportButtonListener listener) {
		this.listenerExportButton = listener;
		
	}
	
	public void addListenerPrintButton(ClickPrintButtonListener listener) {
		this.listenerPrintButton = listener;
		
	}

	public void addListenerAttachButton(ClickAttachButtonListener listener) {
		this.listenerAttachButton = listener;
		
	}
	
	public void addListenerFilterButton(ClickFilterButtonListener listener) {
		this.listenerFilterButton = listener;
		
	}
	
	public interface ClickExportButtonListener extends Serializable {
        public void exportButtonClick(ClickNavigationEvent event);

    }
	
	public interface ClickPrintButtonListener extends Serializable {
        public void printButtonClick(ClickNavigationEvent event);

    }
	
	public interface ClickAttachButtonListener extends Serializable {
        public void attachButtonClick(ClickNavigationEvent event);

    }
	
	public interface ClickFilterButtonListener extends Serializable {
        public void filterButtonClick(ClickNavigationEvent event);

    }
	
	public class ClickNavigationEvent extends ClickEvent {
		private int index;
		private Object register;
		
		public ClickNavigationEvent(Button button, Component source) {
			button.super(source);
			
		}

		public ClickNavigationEvent(Button button, Component source, MouseEventDetails details) {
			button.super(source, details);
			
		}

		public ClickNavigationEvent(Button button, Component source, MouseEventDetails details, Object register, int index) {
			button.super(source, details);
			
			this.index = index;
			this.register = register;
		}

		public int getIndex() {
			return this.index;
			
		}
		
		public Object getRegister() {
			return this.register;
			
		}
		
	  }
		
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// toolbarLayout
		toolbarLayout = buildToolbarLayout();
		mainLayout.addComponent(toolbarLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildToolbarLayout() {
		// common part: create layout
		toolbarLayout = new HorizontalLayout();
		toolbarLayout.setImmediate(false);
		toolbarLayout.setWidth("100.0%");
		toolbarLayout.setHeight("29px");
		toolbarLayout.setMargin(false);
		
		// imgSeparatorGroup
		imgSeparatorGroup = new Embedded();
		imgSeparatorGroup.setImmediate(false);
		imgSeparatorGroup.setWidth("-1px");
		imgSeparatorGroup.setHeight("-1px");
		imgSeparatorGroup.setSource(new ThemeResource("../konekti/images/separator_group.png"));
		imgSeparatorGroup.setType(1);
		imgSeparatorGroup.setMimeType("image/png");
		toolbarLayout.addComponent(imgSeparatorGroup);
		
		// lblExport
		lblExport = new Label();
		lblExport.setImmediate(false);
		lblExport.setWidth("-1px");
		lblExport.setHeight("-1px");
		lblExport.setValue("Exportar:   ");
		toolbarLayout.addComponent(lblExport);
		
		// cmdExport
		cmdExport = new ComboBox();
		cmdExport.setImmediate(false);
		cmdExport.setWidth("120px");
		cmdExport.setHeight("-1px");
		toolbarLayout.addComponent(cmdExport);

		// btnFilter
		btnFilter = new Button();
		//btnFilter.setCaption("A");
		btnFilter.setImmediate(false);
		btnFilter.setWidth("-1px");
		btnFilter.setHeight("-1px");
		btnFilter.setIcon(new ThemeResource("../konekti/images/icons/box-toolbar/funnel.png"));
		toolbarLayout.addComponent(btnFilter);
		
		// btnAttach
		btnAttach = new Button();
		//btnAttach.setCaption("A");
		btnAttach.setImmediate(false);
		btnAttach.setWidth("-1px");
		btnAttach.setHeight("-1px");
		btnAttach.setIcon(new ThemeResource("../konekti/images/icons/box-toolbar/paper-clip.png"));
		toolbarLayout.addComponent(btnAttach);
		
		// btnPrint
		btnPrint = new Button();
		//btnPrint.setCaption("P");
		btnPrint.setImmediate(true);
		btnPrint.setWidth("-1px");
		btnPrint.setHeight("-1px");
		btnPrint.setIcon(new ThemeResource("../konekti/images/icons/box-toolbar/printer.png"));
		toolbarLayout.addComponent(btnPrint);
		toolbarLayout.setExpandRatio(btnPrint, 1.0f);
		
		return toolbarLayout;
	}

}
